# Specify version format
version: "{build}"

platform:
  - Win32
  - x64
  
configuration:
  - Debug
  - Release
  
# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - git config --global core.autocrlf input
  
# clone directory
clone_folder: C:\projects\RetroSpy

skip_commits:
  files:
    - doc/*

# Maximum number of concurrent jobs for the project
max_jobs: 1

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects\RetroSpy
  - cmd: git submodule update --init --recursive

# scripts to run before build
before_build:
  - cmd: cd C:\projects\RetroSpy
  - cmd: md build
  - cmd: cd build
  - cmd: if %PLATFORM% == Win32 cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration%  ..
  - cmd: if %PLATFORM% == x64 cmake -G "%GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%configuration%  ..

build:
  project: C:\projects\RetroSpy\build\retrospy.sln
  parallel: true                             # enable MSBuild parallel builds
  verbosity: minimal                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off
